"""应用层：工作区项目指令文件（AGENTS.md / CLAUDE.md）——发现、预算、注入。

对齐 DSH `packages/context/agent-instructions`，按我们的架构裁掉三处
（完整对照与取舍理由见 agent.md §9）：

- **只在本工作区内发现**。DSH 从 cwd 一路向上找到项目根（`.git`）——我们的工具
  被 sandbox 限制在 workspace 内（`resolve_in_workspace` 拒绝越界），向上发现的
  文件模型根本读不到；注入一份它读不到的约定只会制造幻觉。
- **每次渲染重新求值，不做版本账**。DSH 把指令当一条 user 消息注入一次，所以要用
  `changes`（set/replace/remove + digest）追加增量；我们的注入通道是 system 的
  live 段（`prompt.section` 接 `ctx -> str`，每次模型请求重渲染）——**重算替代
  版本账**，和 todo 用重算替代状态同步是同一个思路。
- **不做 user-global / `.local` 层级**：demo 没有多用户与本地覆盖场景。

三个职责：

1. `scan_nested_instruction_files`：build 时扫一次子目录里的指令文件，**只记相对
   路径**（正文由模型按需 `read_file`，和技能机制同一条路）
2. `InstructionLoader.load`：每次渲染读根目录候选文件，`(mtime, size)` 没变就不
   重读——live 段每请求求值，不缓存就是每请求读盘
3. `InstructionLoader.render`：探测结果 + 预算内正文 → system 段文本；没有文件时
   给出"缺失"状态与创建指引（issue #6 的方案 C）

注入的是**正文**而不是只给路径（与 DSH 一致）：项目约定属于"每轮都该生效"的规则，
放 system 才不依赖模型自觉去读；同时它在一个会话里字节稳定（除非 agent 自己改它），
不会像 todo 状态那样把缓存前缀每步打碎一次。
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

# 候选文件名（对齐 DSH DEFAULT_INSTRUCTION_FILE_CANDIDATES）。
# 按顺序扫描：先命中的先注入，两份都存在时都注入（AGENTS.md 在前）。
INSTRUCTION_FILE_CANDIDATES = ('AGENTS.md', 'CLAUDE.md')

# 预算：单文件 8k 字符、整段 20k 字符。超预算截断并明确告知"用 read_file 读全文"。
# 这是**每轮请求都要背的稳定前缀**，所以宁可小一点、让模型按需去读剩下的部分。
INSTRUCTION_MAX_FILE_CHARS = 8000
INSTRUCTION_MAX_TOTAL_CHARS = 20000

# 子目录清单上限（只列路径，不内联正文）；扫描时多收一条，用于"还有更多"的提示。
INSTRUCTION_MAX_NESTED = 10

# 单文件读取上限（对齐 DSH maxSourceBytes）：超过就不读进内存，只留一条指引，
# 免得一个巨大的 AGENTS.md 把 build/请求拖垮。
INSTRUCTION_MAX_SOURCE_BYTES = 1_048_576

_TRUNCATION_NOTICE = (
    '\n\n(…truncated at {limit} chars; use read_file to read the rest of this file)'
)
_TOO_LARGE_NOTICE = (
    '(this file is {size} bytes — too large to inline; use read_file to read it)'
)

_FOUND_RULE = (
    'Project instructions for this workspace (standing rules): read them before you '
    'change anything and follow them. If they contradict what the code actually does, '
    'ask the user — do not edit this file on your own.'
)
_MISSING_HINT = (
    'This workspace has no project instruction file (looked for AGENTS.md / CLAUDE.md '
    'at the workspace root). Once you know stable, reusable things about this project — '
    'how to run or test it, the layout and dependency rules, conventions, preferences the '
    'user asked to keep — propose writing an AGENTS.md and let the user approve the write. '
    'Never put secrets, temporary state, or unverified guesses in it.'
)


@dataclass(frozen=True)
class InstructionFile:
    """一份要注入的项目指令文件（正文已按预算处理）。

    display 是相对 workspace 的 posix 路径（模型传给 read_file 的写法）；
    truncated 为 True 时 content 末尾已附截断提示。
    """
    path: Path
    display: str
    content: str
    truncated: bool


@dataclass(frozen=True)
class WorkspaceInstructions:
    """一次探测的结果：根目录命中的文件（含正文）+ 子目录清单（只路径）。"""
    files: tuple[InstructionFile, ...] = ()
    nested: tuple[str, ...] = ()

    @property
    def found(self) -> bool:
        return bool(self.files)


def scan_nested_instruction_files(workspace: Path) -> tuple[str, ...]:
    """扫子目录里的指令文件（build 时一次），返回相对 workspace 的 posix 路径。

    用 os.walk 而不是 rglob：可以**原地剪枝**，不下钻进隐藏目录/缓存/依赖——
    rglob('**/AGENTS.md') 会先遍历整棵 node_modules 才轮到过滤。隐藏目录策略
    与 glob 工具一致（`.` 开头或 `__pycache__`）。
    """
    if not workspace.is_dir():
        return ()
    names = set(INSTRUCTION_FILE_CANDIDATES)
    found: list[str] = []
    for dirpath, dirnames, filenames in os.walk(workspace):
        dirnames[:] = [d for d in dirnames if not (d.startswith('.') or d == '__pycache__')]
        rel_dir = Path(dirpath).relative_to(workspace)
        if rel_dir.parts:                      # 根目录那份由 files 承载，不进清单
            found.extend((rel_dir / name).as_posix() for name in sorted(names & set(filenames)))
        if len(found) > INSTRUCTION_MAX_NESTED:
            break                              # 只多收一条：够判断"还有更多"
    found.sort()
    return tuple(found[:INSTRUCTION_MAX_NESTED + 1])


class InstructionLoader:
    """带 stat 缓存的加载器：live 段每请求求值，所以文件没变就不重读。

    一个 agent 一个实例（`build_agent` 创建并闭包给 live 段）。缓存键是
    `(mtime_ns, size)`——内容按路径+时间戳记忆，改过的文件自然失效。
    """

    def __init__(self, workspace: Path) -> None:
        self._workspace = workspace
        self._nested = scan_nested_instruction_files(workspace)
        self._cache: dict[Path, tuple[tuple[int, int], str]] = {}

    @property
    def nested(self) -> tuple[str, ...]:
        return self._nested

    def load(self) -> WorkspaceInstructions:
        """探测 + 读正文（按预算）→ 不可变的探测结果。"""
        files: list[InstructionFile] = []
        used = 0
        for name in INSTRUCTION_FILE_CANDIDATES:
            text = self._read(self._workspace / name)
            if text is None:
                continue
            budget = min(INSTRUCTION_MAX_FILE_CHARS, INSTRUCTION_MAX_TOTAL_CHARS - used)
            if budget <= 0:
                break
            truncated = len(text) > budget
            if truncated:
                content = text[:budget].rstrip() + _TRUNCATION_NOTICE.format(limit=budget)
            else:
                # 末尾空行没有语义：段与段之间的空行由渲染统一加，去掉免得出现三连空行
                content = text.rstrip()
            files.append(InstructionFile(
                path=self._workspace / name, display=name, content=content, truncated=truncated,
            ))
            used += len(content)
        return WorkspaceInstructions(files=tuple(files), nested=self._nested)

    def render(self) -> str:
        """system 段文本（live 段 provider：每次模型请求求值一次）。"""
        return render_workspace_instructions(self.load())

    def _read(self, path: Path) -> str | None:
        """读一份候选文件；缺失/读不动 → None（探测不到不算错误）。"""
        try:
            stat = path.stat()
        except OSError:
            return None
        if not path.is_file():
            return None
        if stat.st_size > INSTRUCTION_MAX_SOURCE_BYTES:
            return _TOO_LARGE_NOTICE.format(size=stat.st_size)
        key = (stat.st_mtime_ns, stat.st_size)
        cached = self._cache.get(path)
        if cached is not None and cached[0] == key:
            return cached[1]
        try:
            text = path.read_text(encoding='utf-8', errors='replace')
        except OSError:
            return None
        self._cache[path] = (key, text)
        return text


def render_workspace_instructions(instructions: WorkspaceInstructions) -> str:
    """探测结果 → system 段文本（纯函数，便于直接断言）。

    有文件：`<workspace_instructions files="…">` + 每份 `Instructions from: <路径>`
    + 正文；没有：同一标签下给"缺失"状态 + 创建指引（模型据此提议创建，写入仍走
    approval）。子目录清单两种情况都可能追加（根目录没有、子目录却有的仓库存在）。
    """
    if instructions.files:
        head = (
            f'<workspace_instructions files="{", ".join(f.display for f in instructions.files)}">\n'
            f'{_FOUND_RULE}'
        )
        body = '\n\n'.join(
            f'Instructions from: {f.display}\n\n{f.content}' for f in instructions.files
        )
        parts = [head, body, '</workspace_instructions>']
    else:
        parts = [f'<workspace_instructions files="none">\n{_MISSING_HINT}\n</workspace_instructions>']
    if instructions.nested:
        shown = instructions.nested[:INSTRUCTION_MAX_NESTED]
        line = ('Subdirectory instruction files (read the relevant one before working in '
                'that directory): ' + ', '.join(shown))
        hidden = len(instructions.nested) - len(shown)
        if hidden > 0:
            line += f' — and at least {hidden} more (glob **/AGENTS.md)'
        parts.append(line)
    return '\n\n'.join(parts)
